name: R-CMD-check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install system dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R dependencies
        run: |
          R -e 'install.packages(c("remotes", "rcmdcheck"))'
          R -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Check package
        run: |
          R -e 'rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "warning")'
